/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 07:14:38 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */



/* Create Tables */

CREATE TABLE "ADM_TINFO"
(
	"INFO_INFO" integer NOT NULL,
	"INFO_TIPO" varchar(100)	 NULL,
	"VALOR" decimal(10,5) NULL
)
;


