/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 08:49:25 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */



/* Create Tables */

CREATE TABLE "ADM_TCOMB"
(
	"COMB_COMB" integer NOT NULL,
	"COMB_NOMB" varchar(50)	 NULL,
	"COMB_ORDE" integer NULL,
	"COMB_CAJA" integer NULL
)
;


