/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 07:15:53 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */



/* Create Tables */

CREATE TABLE "ADM_TGRUP"
(
	"GRUP_GRUP" integer NOT NULL,
	"GRUP_RANG" varchar(50)	 NULL
)
;


