/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 07:16:33 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "ADM_TPRGR" CASCADE
;

/* Create Tables */

CREATE TABLE "ADM_TPRGR"
(
	"PRGR_PRGR" integer NOT NULL,
	"PRGR_PROD" integer NULL,
	"PRGR_GRUP" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "ADM_TPRGR" ADD CONSTRAINT "PK_ADM_TPRGR"
	PRIMARY KEY ("PRGR_PRGR")
;

CREATE INDEX "IXFK_ADM_TPRGR_ADM_TGRUP" ON "ADM_TPRGR" ("PRGR_GRUP" ASC)
;

CREATE INDEX "IXFK_ADM_TPRGR_ADM_TPRODUCTO" ON "ADM_TPRGR" ("PRGR_PROD" ASC)
;


