/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 18-mar-2016 01:59:08 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE ADM_TINFO
(
	INFO_INFO integer NOT NULL,
	INFO_TIPO varchar(100)	 NULL,
	VALOR decimal(10,5) NULL,
	INFO_PROD integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE ADM_TINFO ADD CONSTRAINT PK_ADM_INFONUTRICIONAL
	PRIMARY KEY (INFO_INFO)
;

CREATE INDEX IXFK_ADM_TINFO_ADM_TPROD ON ADM_TINFO (INFO_PROD ASC)
;


