/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 07:15:33 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE ADM_TMARC
(
	MARC_MARC integer NOT NULL,
	MARC_NOMB varchar(100)	 NULL
)
;


