/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 07:15:15 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "ADM_TCATE" CASCADE
;

/* Create Tables */

CREATE TABLE "ADM_TCATE"
(
	"CATE_CATE" integer NOT NULL,
	"CATE_NOMB" varchar(100)	 NULL
)
;

