/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 07:17:43 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */



/* Create Tables */

CREATE TABLE CLI_TDIA
(
	DIA_DIA integer NOT NULL,
	DIA_FECH date NULL,
	DIA_LIST integer NULL,
	DIA_NINO integer NULL
)
;


