/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 07:18:12 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "CLI_TLIST" CASCADE
;

/* Create Tables */

CREATE TABLE "CLI_TLIST"
(
	"LIST_LIST" integer NOT NULL,
	"LIST_PROD" integer NULL,
	"LIST_DIA" integer NULL
)
;

