/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 07:17:00 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "CLI_TPADR" CASCADE
;

/* Create Tables */

CREATE TABLE "CLI_TPADR"
(
	"PADR_PADR" integer NOT NULL,
	"PADR_NOMB" varchar(100)	 NULL,
	"PADR_TELE" varchar(50)	 NULL,
	"PADR_DIRE" varchar(100)	 NULL,
	"PADR_EMAI" varchar(100)	 NULL,
	"PADR_CONT" varchar(50)	 NULL,
	"PADR_PRIM" boolean NULL,
	"PADR_NCON" varchar(10)	 NULL
)
;


