/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 07:30:23 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE CLI_TTARJ
(
	TARJ_TARJ integer NOT NULL,
	TARJ_NOMB varchar(50)	 NULL,
	TARJ_NUME varchar(50)	 NULL,
	TARJ_PADR integer NULL
)
;


