/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 09:15:06 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */



/* Create Tables */

CREATE TABLE "CLI_TLIST"
(
	"LIST_LIST" integer NOT NULL,
	"LIST_PROD" integer NULL,
	"LIST_DIA" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "CLI_TLIST" ADD CONSTRAINT "PK_CLI_TLIST"
	PRIMARY KEY ("LIST_LIST")
;

CREATE INDEX "IXFK_CLI_TLIST_ADM_TPROD" ON "CLI_TLIST" ("LIST_PROD" ASC)
;

CREATE INDEX "IXFK_CLI_TLIST_CLI_TDIA" ON "CLI_TLIST" ("LIST_DIA" ASC)
;


