ALTER TABLE ADM_TCOMB ADD CONSTRAINT PK_ADM_TCOMB
	PRIMARY KEY (COMB_COMB)
;

CREATE INDEX IXFK_ADM_TCOMB_ADM_TCAJA ON ADM_TCOMB (COMB_CAJA ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE ADM_TCOMB ADD CONSTRAINT FK_ADM_TCOMB_ADM_TCAJA
	FOREIGN KEY (COMB_CAJA) REFERENCES ADM_TCAJA (CAJA_CAJA) ON DELETE No Action ON UPDATE No Action
;