/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 08:49:25 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "ADM_TCOMB" CASCADE
;

/* Create Tables */

CREATE TABLE "ADM_TCOMB"
(
	"COMB_COMB" integer NOT NULL,
	"COMB_NOMB" varchar(50)	 NULL,
	"COMB_ORDE" integer NULL,
	"COMB_CAJA" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "ADM_TCOMB" ADD CONSTRAINT "PK_ADM_TCOMB"
	PRIMARY KEY ("COMB_COMB")
;

CREATE INDEX "IXFK_ADM_TCOMB_ADM_TCAJA" ON "ADM_TCOMB" ("COMB_CAJA" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "ADM_TCOMB" ADD CONSTRAINT "FK_ADM_TCOMB_ADM_TCAJA"
	FOREIGN KEY ("COMB_CAJA") REFERENCES "ADM_TCAJA" ("CAJA_CAJA") ON DELETE No Action ON UPDATE No Action
;
