/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 09:20:57 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "CLI_TLIST" CASCADE
;

/* Create Tables */

CREATE TABLE "CLI_TLIST"
(
	"LIST_LIST" integer NOT NULL,
	"LIST_PROD" integer NULL,
	"LIST_DIA" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "CLI_TLIST" ADD CONSTRAINT "PK_CLI_TLIST"
	PRIMARY KEY ("LIST_LIST")
;

CREATE INDEX "IXFK_CLI_TLIST_ADM_TPROD" ON "CLI_TLIST" ("LIST_PROD" ASC)
;

CREATE INDEX "IXFK_CLI_TLIST_CLI_TDIA" ON "CLI_TLIST" ("LIST_DIA" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "CLI_TLIST" ADD CONSTRAINT "FK_CLI_TLIST_ADM_TPROD"
	FOREIGN KEY ("LIST_PROD") REFERENCES "ADM_TPROD" ("PROD_PROD") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "CLI_TLIST" ADD CONSTRAINT "FK_CLI_TLIST_CLI_TDIA"
	FOREIGN KEY ("LIST_DIA") REFERENCES "CLI_TDIA" ("DIA_DIA") ON DELETE No Action ON UPDATE No Action
;
