/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 17-mar-2016 07:30:23 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "CLI_TTARJ" CASCADE
;

/* Create Tables */

CREATE TABLE "CLI_TTARJ"
(
	"TARJ_TARJ" integer NOT NULL,
	"TARJ_NOMB" varchar(50)	 NULL,
	"TARJ_NUME" varchar(50)	 NULL,
	"TARJ_PADR" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "CLI_TTARJ" ADD CONSTRAINT "PK_CLI_TTAR"
	PRIMARY KEY ("TARJ_TARJ")
;

CREATE INDEX "IXFK_CLI_TTARJ_CLI_TPADR" ON "CLI_TTARJ" ("TARJ_PADR" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "CLI_TTARJ" ADD CONSTRAINT "FK_CLI_TTARJ_CLI_TPADR"
	FOREIGN KEY ("TARJ_PADR") REFERENCES "CLI_TPADR" ("PADR_PADR") ON DELETE No Action ON UPDATE No Action
;
