\i /DDL/create/ADM_TINFO.sql;
\i /DDL/create/ADM_TCATE.sql;
\i /DDL/create/ADM_TMARC.sql;
\i /DDL/create/ADM_TGRUP.sql;
\i /DDL/create/ADM_TPROD.sql;
\i /DDL/create/ADM_TGRPR.sql;
\i /DDL/create/CLI_TPADR.sql;
\i /DDL/create/CLI_TNINO.sql;
\i /DDL/create/CLI_TDIA.sql;
\i /DDL/create/CLI_TLIST.sql;
\i /DDL/create/CLI_TNLON.sql;
\i /DDL/create/CLI_TFAVO.sql;
\i /DDL/create/CLI_TTARJ.sql;
\i /DDL/create/CLI_TFEED.sql;
\i /DDL/create/ADM_TCAJA.sql;
\i /DDL/create/ADM_TCOMB.sql;
\i /DDL/create/ADM_TITEM.sql;

